---
services:
  pyro-ansible:
    container_name: pyro-ansible
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./roles:/ansible/roles
      - ./docker/Makefile:/ansible/Makefile
      - ./docker/ansible.cfg:/ansible/ansible.cfg:ro
      - ${VAULT_PASSWORD_FILE}:/ansible/.vault_passwrd:ro
      - ${SSH_PRIVATE_KEY_FILE}:/ansible/id_rsa:ro
      - ./bin/common/Makefile:/ansible/MakefileCommon
      - ${REPO_PATH}/inventory/group_vars:/ansible/inventory/group_vars
      - ${REPO_PATH}/host_vars:/ansible/inventory/host_vars
      - ${REPO_PATH}/inventory:/ansible/inventory
    stdin_open: true
    tty: true
    command: "sh"

  semaphore:
    container_name: semaphore
    ports:
      - "3000:3000"
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    volumes:
      - ./:/app
      - semaphore-config:/etc/semaphore # config.json location
      - semaphore-database:/var/lib/semaphore # database.boltdb location
      - ~/.ssh:/root/.ssh/:ro,z
volumes:
  semaphore-config:
    driver: local
  semaphore-database:
    driver: local
