---
- name: Install nmcli
  ansible.builtin.apt:
    name: network-manager
    state: present

- name: Check if Wi-Fi connection exists
  ansible.builtin.command: nmcli -t -f NAME con show
  register: nmcli_connections
  changed_when: false

- name: Configure Wi-Fi if SSID is provided and not already configured
  ansible.builtin.shell: >
    nmcli con add type wifi ifname wlan0 con-name {{ wifi_ssid }}
    ssid {{ wifi_ssid }} wifi-sec.key-mgmt wpa-psk
    wifi-sec.psk {{ wifi_password }} connection.autoconnect yes
  when:
    - wifi_ssid != ""
    - wifi_ssid not in nmcli_connections.stdout.splitlines()
  register: wifi_result
  ignore_errors: yes
  changed_when: wifi_result.rc == 0

- name: Debug Wi-Fi result
  ansible.builtin.debug:
    var: wifi_result
