---
- name: Install nmcli
  ansible.builtin.apt:
    name: network-manager
    state: present

- name: Configure Wi-Fi connections
  ansible.builtin.shell: |
    if nmcli con show "{{ item.ssid }}" &>/dev/null; then
      nmcli con mod "{{ item.ssid }}" \
        wifi-sec.psk "{{ item.password }}" \
        connection.autoconnect-priority {{ item.priority | default(0) }} \
        connection.autoconnect-retries 0
    else
      nmcli con add type wifi ifname wlan0 con-name "{{ item.ssid }}" \
        ssid "{{ item.ssid }}" wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "{{ item.password }}" connection.autoconnect yes \
        connection.autoconnect-priority {{ item.priority | default(0) }} \
        connection.autoconnect-retries 0
    fi
  loop: "{{ wifi_connections }}"
  changed_when: true
