---
- name: Ensure working directory exists
  ansible.builtin.file:
    path: "{{ engine_cron_working_dir }}"
    state: directory
    mode: '0755'

- name: Generate main pi watchdog .env file
  ansible.builtin.template:
    src: watchdog_main.env.j2
    dest: /home/pi/watchdog_main.env
    owner: pi
    group: pi
    mode: "0644"
  when: pi_zero_hostname != ""

- name: Add cron job for main pi watchdog
  ansible.builtin.cron:
    name: "Main pi watchdog"
    minute: "5,15,25,35,45,55"
    job: "/usr/bin/python3 {{ engine_cron_working_dir }}/watchdog/main_pi/watchdog.py >> /home/pi/watchdog_main.log 2>&1"
    user: pi
  when: pi_zero_hostname != ""
