---
- name: Récupérer les données des Raspberry Pi
  ansible.builtin.set_fact:
    # mediamtx_users: "{{ mediamtx_users | default([]) + [{'user': item, 'pass': hostvars[item]['mediamtx_pass']}] }}"
    mediamtx_paths: "{{ mediamtx_paths | default([]) + [{'name': item}] }}"
  loop: "{{ groups['engine_servers'] }}"

- name: Appliquer le template de configuration MediaMTX
  ansible.builtin.template:
    src: mediamtx.yml.j2
    dest: "{{ mediamtx_config_file }}"
    mode: '0644'
    backup: yes

- name: Redémarrer le conteneur MediaMTX
  community.docker.docker_container:
    name: mediamtx
    restart: true
