---
- name: Retrieve Raspberry Pi/engine data
  ansible.builtin.set_fact:
    # mediamtx_users: "{{ mediamtx_users | default([]) + [{'user': item, 'pass': hostvars[item]['mediamtx_pass']}] }}"
    mediamtx_paths: "{{ mediamtx_paths | default([]) + [{'name': item}] }}"
  loop: "{{ groups['engine_servers'] }}"

- name: Apply MediaMTX configuration template
  ansible.builtin.template:
    src: mediamtx.yml.j2
    dest: "{{ mediamtx_config_file }}"
    mode: '0644'
    backup: yes
  notify: Restart MediaMTX container

- name: Fetch mediamtx config backup to control host
  ansible.builtin.fetch:
    src: "{{ mediamtx_config_file }}"
    dest: "/ansible/backups/mediamtx/mediamtx.yml"
    flat: yes
