---
- name: Loading environment variables
  tags: always
  ansible.builtin.set_fact:
    admin_login: '{{ lookup("env", "SUPERADMIN_LOGIN") }}'
    admin_pwd: '{{ lookup("env", "SUPERADMIN_PWD") }}'
    admin_org: '{{ lookup("env", "SUPERADMIN_ORG") }}'

- name: Check Engine variables
  ansible.builtin.fail:
    msg: "Variable '{{ item.name }}' is empty or None."
  loop:
    - { name: "api_dns",          value: "{{ api_dns }}" }             # group_var/all
    - { name: "pyro_engine_git_ref",    value: "{{ pyro_engine_git_ref }}" }    # group_var/engine_servers
    - { name: "pyro_engine_docker_tag", value: "{{ pyro_engine_docker_tag }}" } # group_var/engine_servers
    - { name: "CAM_USER",         value: "{{ CAM_USER }}" }            # group_var/all
    - { name: "CAM_PWD",          value: "{{ CAM_PWD }}" }             # group_var/all
    - { name: "config_json",      value: "{{ config_json }}" }         # host_var
    - { name: "ansible_password", value: "{{ ansible_password }}" }    # host_var
    - { name: "admin_login",      value: "{{ admin_login }}" }         # .env
    - { name: "admin_pwd",        value: "{{ admin_pwd }}" }           # .env
    - { name: "S3_ENDPOINT_URL",  value: "{{ S3_ENDPOINT_URL }}" }     # inventory vars
    - { name: "S3_ACCESS_KEY",    value: "{{ S3_ACCESS_KEY }}" }       # inventory vars
    - { name: "S3_SECRET_KEY",    value: "{{ S3_SECRET_KEY }}" }       # inventory vars
    - { name: "S3_REGION",        value: "{{ S3_REGION }}" }           # inventory vars
    - { name: "alloy_config",     value: "{{ alloy_config }}" }        # group_var/engine
  when:
    - inventory_hostname in groups["engine_servers"]
    - item.value is none or item.value | length == 0
  no_log: false

- name: Check API variables. no_log=true
  ansible.builtin.fail:
    msg: "Variable '{{ item.name }}' is empty or None."
  loop:
    - { name: "admin_login",      value: "{{ admin_login }}" }
    - { name: "admin_pwd",        value: "{{ admin_pwd }}" }
    - { name: "admin_org",        value: "{{ admin_org }}" }
    - { name: "S3_ENDPOINT_URL",  value: "{{ S3_ENDPOINT_URL }}" }
    - { name: "S3_ACCESS_KEY",    value: "{{ S3_ACCESS_KEY }}" }
    - { name: "S3_SECRET_KEY",    value: "{{ S3_SECRET_KEY }}" }
    - { name: "S3_REGION",        value: "{{ S3_REGION }}" }
    # - { name: "S3_PROXY_URL",   value: "{{ S3_PROXY_URL }}" }
    - { name: "POSTGRES_USER",    value: "{{ POSTGRES_USER }}" }
    - { name: "POSTGRES_PASSWORD", value: "{{ POSTGRES_PASSWORD }}" }
    - { name: "POSTGRES_DB",      value: "{{ POSTGRES_DB }}" }
    - { name: "prefix",           value: "{{ prefix }}" }
  when:
    - inventory_hostname in groups["alert_server"]
    - item.value is none or item.value | length == 0
  no_log: true

- name: Check Plateform variables. no_log=true
  ansible.builtin.fail:
    msg: "Variable '{{ item.name }}' is empty or None."
  loop:
    - { name: "api_dns",     value: "{{ api_dns }}" }
    - { name: "admin_login", value: "{{ admin_login }}" }  # DOES THE PLATFORM REALLY NEED ADMIN PWD ?
    - { name: "admin_pwd",   value: "{{ admin_pwd }}" }
    - { name: "prefix",      value: "{{ prefix }}" }
  when:
    - inventory_hostname in groups["platform_py_server"]
    - item.value is none or item.value | length == 0
  no_log: true

- name: Retrieve the list of groups
  ansible.builtin.set_fact:
    group_list:
      - openvpn
      - platform_py_server
      - alert_server

- name: Verify that each group contains only one host
  ansible.builtin.assert:
    that:
      - "groups[item] | length <= 1"
    fail_msg: "The'{{ item }}' group contains more than one server"
    success_msg: "The '{{ item }}' does indeed contain a single server."
  loop: "{{ group_list }}"
