---
- name: Check watchdog daemon status on multiple hosts
  hosts: engine_servers:!alert_server:!platform_server
  become: yes  # Run with sudo/root privileges, required for service status checking
  gather_facts: no  # Disable facts gathering if not needed

  tasks:
    - name: Check if watchdog service is running
      ansible.builtin.systemd:
        name: watchdog
        state: started
      register: watchdog_status

    - name: Fail if watchdog service is not started
      ansible.builtin.fail:
        msg: "Watchdog service is not running on {{ inventory_hostname }}."
      when: watchdog_status.state != 'started'
