---
- name: Verify Ansible version
  hosts: all
  become: true
  tasks:
    - name: Ensure Ansible version is 2.17 or higher
      ansible.builtin.assert:
        that:
          - ansible_version.minor | int >= 17
        fail_msg: "Ansible version must be 2.17 or higher."

- name: Check vars
  hosts: platform_py_server:openvpn:mediamtx_server
  become: true
  roles:
    - check_vars

- name: Upgrade, install git and docker
  hosts: alert_server:platform_py_server:platform_react_server:openvpn:mediamtx_server
  become: true
  roles:
    - common
    - docker

- name: Deploy Openvpn
  hosts: openvpn
  become: true
  roles:
    - pyronear.openvpn

- name: Deploy Mediamtx
  hosts: mediamtx_server
  become: true
  roles:
    - mediamtx

- name: Deploy Docker Compose Servers
  hosts: platform_py_server:annotation_server
  become: true
  roles:
    - servers

- name: Deploy Docker Compose applications
  hosts: platform_py_server:alert_server
  become: true
  serial: 1
  tasks:
    - name: Run client-specific tasks
      ansible.builtin.include_role:
        name: pyronear.openvpn
        tasks_from: install_client.yml

    - name: Remplacer 'redirect-gateway def1' par 'route 192.168.255.0 255.255.255.0'
      ansible.builtin.replace:
        path: /etc/openvpn/client.conf
        regexp: '^redirect-gateway def1$'
        replace: 'route 192.168.255.0 255.255.255.0'

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

- name: Deploy vpn for platform_react_server
  hosts: platform_react_server
  become: true
  tasks:
    - name: Run client-specific tasks
      ansible.builtin.include_role:
        name: pyronear.openvpn
        tasks_from: install_client.yml

    - name: Remplacer 'redirect-gateway def1' par 'route 192.168.255.0 255.255.255.0'
      ansible.builtin.replace:
        path: /etc/openvpn/client.conf
        regexp: '^redirect-gateway def1$'
        replace: 'route 192.168.255.0 255.255.255.0'

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

- name: Deploy service platform_react_server
  hosts: platform_react_server
  become: true
  roles:
    - role: platform_react
      tags:
        - app

- name: Deploy service alert_api
  hosts: alert_server
  become: true
  roles:
    - role: alert_api
      tags:
        - app
