---
- name: Verify Ansible version and setup servers
  hosts: engine_servers
  become: true
  tasks:
    - name: Ensure Ansible version is 2.17 or higher
      ansible.builtin.assert:
        that:
          - ansible_version.minor | int >= 17
        fail_msg: "Ansible version must be 2.17 or higher : {{ ansible_version.minor }}"


    - name: Ensure Docker Compose containers are running
      community.docker.docker_compose_v2:
        project_src: /home/{{ app_name }}/
        state: absent
