---
- name: Base setup - check Ansible version then upgrade packages, git, WiFi, Docker
  hosts: engine_servers
  become: true
  pre_tasks:
    - name: Ensure Ansible version is 2.17 or higher
      ansible.builtin.assert:
        that:
          - ansible_version.minor | int >= 17
        fail_msg: "Ansible version must be 2.17 or higher."
      run_once: true

  roles:
    - common
    - wifi
    - docker

- name: Configure reverse SSH tunnel
  hosts: engine_servers
  become: true 
  serial: 1
  roles:
    - reverse_ssh

- name: Register engine streams on mediamtx server
  hosts: mediamtx_server
  become: true
  tasks:

    - name: Update mediamtx config with new engine streams
      ansible.builtin.include_role:
        name: mediamtx
        tasks_from: update_conf.yml

- name: Install Alloy monitoring agent
  hosts: engine_servers
  become: true
  tasks:
    - name: Install Alloy
      ansible.builtin.include_role:
        name: grafana.grafana.alloy
      vars:
        config: "{{ alloy_config }}"

- name: Install OpenVPN client and reboot
  hosts: engine_servers
  become: true
  serial: 1
  tasks:
    - name: Install OpenVPN client
      ansible.builtin.include_role:
        name: pyronear.openvpn
        tasks_from: install_client.yml

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

- name: Configure static IP and reboot
  hosts: engine_servers
  become: true
  serial: 1
  roles:
    - static_ip
