---
- name: Verify Ansible version and setup servers
  hosts: engine_servers
  become: true
  tasks:
    - name: Ensure Ansible version is 2.17 or higher
      ansible.builtin.assert:
        that:
          - ansible_version.minor | int >= 17
        fail_msg: "Ansible version must be 2.17 or higher."

  roles:
    - common
    - docker

- name: Apply reverse SSH role one host at a time
  hosts: engine_servers
  become: true
  serial: 1
  roles:
    - reverse_ssh

- name: Deploy Docker Compose applications
  hosts: engine_servers
  become: true
  serial: 1
  tasks:
    - name: Run client-specific tasks
      ansible.builtin.include_role:
        name: pyronear.openvpn
        tasks_from: install_client.yml

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
