---
- name: Verify Ansible version and setup servers
  hosts: engine_servers
  become: true
  tasks:
    - name: Ensure Ansible version is 2.17 or higher
      ansible.builtin.assert:
        that:
          - ansible_version.minor | int >= 17
        fail_msg: "Ansible version must be 2.17 or higher : {{ ansible_version.minor }}"

  roles:
    - check_vars
    - engine
