---
- name: Check revser ssh variables. no_log=true
  ansible.builtin.fail:
    msg: item is empty or None.
  loop:
    - "{{ reverse_ssh_port }}"
  when:
    - item == None

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: /home/{{ ansible_user }}/.ssh/id_rsa

- name: Read generated public key into a variable
  ansible.builtin.slurp:
    src: /home/{{ ansible_user }}/.ssh/id_rsa.pub
  register: ssh_pub_key_raw

- name: Decode public key
  ansible.builtin.set_fact:
    ssh_pub_key: "{{ ssh_pub_key_raw['content'] | b64decode }}"

- name: Add public key to authorized_keys on reverse SSH server
  ansible.posix.authorized_key:
    user: ubuntu
    key: "{{ ssh_pub_key }}"
  delegate_to: reverse_ssh_server

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/known_hosts
    state: touch
    mode: '0644'

- name: Add remote server pub print in known_hosts
  ansible.builtin.known_hosts:
    path: /home/{{ ansible_user }}/.ssh/known_hosts
    name: "{{ hostvars['reverse_ssh_server']['ansible_host'] }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 ' ~ hostvars['reverse_ssh_server']['ansible_host']) }}"
    state: present

- name: Copy reverse-ssh.service file
  ansible.builtin.template:
    src: "reverse-ssh.service.j2"
    dest: /etc/systemd/system/reverse-ssh.service
    mode: '0644'

- name: Fix permissions on private key
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/id_rsa
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Fix permissions on public key
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/id_rsa.pub
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Fix permissions on known_hosts
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.ssh/known_hosts
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Restart service reverse-ssh
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    daemon_reload: true
    name: reverse-ssh
