---

- name: Create a network
  community.docker.docker_network:
    name: web

- name: Create working directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ platform_react_working_dir_react }}"
    - "{{ platform_react_working_dir_react }}/config"
    - "{{ platform_react_working_dir_react }}/logs"
    - "{{ platform_react_working_dir_traefik }}"

- name: Stop all services
  community.docker.docker_compose_v2:
    project_src: "{{ platform_react_working_dir_react }}"
    state: absent
    remove_images: all
  ignore_errors: true

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ platform_react_working_dir_react }}/docker-compose.yml"
    mode: "0644"

- name: Install config files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ platform_react_working_dir_react }}/config/{{ item }}"
    mode: "0644"
  with_items:
    - app-config-prod.js
    - sites_live_access_prod.json

- name: Create empty acme file for traefik
  ansible.builtin.copy:
    content: ""
    dest: "{{ platform_react_working_dir_traefik }}/acme.json"
    force: false
    group: sys
    mode: 0600

- name: Create conf file for traefik
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: "{{ platform_react_working_dir_traefik }}/traefik.toml"
    group: sys
    mode: "0600"

- name: Docker Compose start and verify containers are running
  community.docker.docker_compose_v2:
    project_src: "{{ platform_react_working_dir_react }}"
    wait: true